import * as THREE from './vendor/three.module.js';
import { enemyDamage, enemyProfile, playerDamage } from './battle-rules.js?v=battle-balance-3';
import { chooseEnemyMove } from './battle-ai.js?v=battle-balance-2';
import { clearPlayerBattleEffects, createBattleState } from './battle-state.js?v=battle-flow-2';
import * as BattleStatus from './battle-status.js';
import { renderBattleView } from './battle-render.js';
let loadedSprites=0;
const data=window.THREE_BATTLE_DATA||{moves:[],species:[]}; const starterKey=localStorage.getItem('vl_three_battle_starter'); const starterRecord=window.DataByteSession?.party?.().find(item=>(item.uid||item.id)===starterKey||item.id===starterKey); const starterId=starterRecord?.id||starterKey; const starterAliases={kindlekid:{id:'kindlekid',name:'KindleKid',sprite:'placeholder.png',color:0xff9f43},coincalf:{id:'coincalf',name:'CoinCalf',sprite:'placeholder.png',color:0xffd166},gemneye:{id:'gemneye',name:'Gem-N-Eye',sprite:'gem-n-eye.png',color:0xc084fc},sixela:{id:'sixela',name:'6.ela',sprite:'6-ela.png',color:0x8bd450},pixelpup:{id:'pixelpup',name:'PixelPup',sprite:'placeholder.png',color:0x60a5fa},centaurcher:{id:'centaurcher',name:'Centaurcher',sprite:'placeholder.png',color:0xd97706},clockadile:{id:'clockadile',name:'Clockadile',sprite:'placeholder.png',color:0x84cc16},aquobit:{id:'aquobit',name:'AquoBit',sprite:'placeholder.png',color:0x22d3ee}}; const ps={...(data.species.find(s=>s.id===starterId)||starterAliases[starterId]||data.species[0]||{name:'Leovolt',sprite:'leovolt.png',color:0x45d8ff}),...(starterRecord||{})}; const profileXp=window.DataByteProgression?.xp?.()||0; const encounterPool=data.species.filter(s=>s.id!=='placeholder'&&!/pending/i.test(s.name||'')&&(window.DataByteProgressionData?.wildEligible?.(s,profileXp)??((window.DataByteProgressionData?.stageFor?.(s)||1)===1))); const es=encounterPool[Math.floor(Math.random()*Math.max(1,encounterPool.length))]||{id:'scorpyone',name:'Scorpyone',sprite:'scorpyone.png',color:0xff6689}; const creatures={player:{...ps,sprite:starterRecord?.sprite||'./data/sprites/'+ps.sprite,hp:starterRecord?.hp??100,maxHp:starterRecord?.maxHp??100},enemy:{...es,sprite:'./data/sprites/'+es.sprite,hp:100,maxHp:100}};
if(/pending/i.test(creatures.enemy.name||''))creatures.enemy.name='Unknown Signal';
window.DataByteBattle={canonicalLoop:true,getState:()=>state,healPlayer(amount){if(!state||state.busy||state.over)return false;const before=creatures.player.hp;creatures.player.hp=Math.min(creatures.player.maxHp,creatures.player.hp+amount);persistPlayerHp();state.message=`${creatures.player.name} used a Signal Patch and recovered ${creatures.player.hp-before} HP.`;consumeItemTurn();return true},boost(){if(!state||state.busy||state.over)return false;state.capturePressure=Math.min(35,(state.capturePressure||0)+12);state.message=`Signal Boost raised capture pressure to ${state.capturePressure}%.`;consumeItemTurn();return true},repair(){if(!state||state.busy||state.over)return false;const before=creatures.player.hp;creatures.player.hp=Math.min(creatures.player.maxHp,creatures.player.hp+35);persistPlayerHp();state.message=`Repair Pulse restored ${creatures.player.hp-before} HP.`;consumeItemTurn();return true},message(text){if(state){state.message=text;render()}}};
window.DataByteBattleAI={chooseEnemyMove};
window.addEventListener('databyte:starter-updated',event=>{const next=session?.party?.().find(item=>(item.uid||item.id)===event.detail?.uid||item.id===event.detail?.id);if(!next)return;Object.assign(creatures.player,next,{sprite:next.sprite,hp:next.hp??100,maxHp:next.maxHp??100});$('playerName')?.replaceChildren(document.createTextNode(next.name.toUpperCase()));renderMoves();if(scene&&playerMesh){scene.remove(playerMesh);const source=data.species.find(s=>s.id===next.id)||next;playerMesh=makeFighter({...source,sprite:next.sprite},-3);scene.add(playerMesh);resize()}if(state){state.message=`${next.name} entered the battle.`;render()}});
window.addEventListener('databyte:deploy-requested',()=>{if(state){state.over=false;state.busy=false;state.guarding=false;state.message=`${creatures.player.name} deployed. Continue the battle.`;render()}});
const session=window.DataByteSession; const moveElements={'Signal Strike':'Signal','Volt Pounce':'Volt','Mirror Feint':'Mirror','Screen Guard':'Shield'}; const moveInteractions={'Signal Strike':{Pristine:0,Stained:0,Null:0},'Volt Pounce':{Pristine:2,Stained:0,Null:-1},'Mirror Feint':{Pristine:0,Stained:1,Null:1},'Screen Guard':{Pristine:2,Stained:0,Null:-1}}; let moves=[]; const mapMove=m=>({id:m.id,name:m.name,moveType:m.moveType||((Number(m.power)||0)>0?'attack':'defense'),configuration:m.configuration||'Unassigned',power:Number(m.power)||0,accuracy:m.accuracy,downloadEffect:m.downloadEffect,stabilityEffect:m.stabilityEffect||0,statusEffect:m.statusEffect||null,element:moveElements[m.name]||m.configuration||'Signal',alignmentInteractions:m.alignmentInteractions||moveInteractions[m.name]||{},copy:m.description}); function resolveMoves(id){const species=session?.roster?.().find(item=>item.id===id)||data.species.find(item=>item.id===id)||{};const raw=window.THREE_BATTLE_MOVE_FOR_SPECIES?.(id,species)||data.moves;return raw.map(mapMove).slice(0,4)} function renderMoves(){moves=resolveMoves(creatures.player.id);$('actions').innerHTML=moves.map((m,i)=>`<button class="action" data-move="${i}"><b>${m.name}</b><span>${m.copy} · ${m.power<0?'+'+(-m.power)+' HP':m.power+' DMG'}</span></button>`).join('')}
const $=id=>document.getElementById(id); let state, reset, act, enemyTurn, scanTimer=null, scanHandoffTimer=null;
function currentPlayerRecord(){const active=session?.starter?.();return session?.party?.().find(item=>(item.uid||item.id)===active)||session?.party?.().find(item=>item.id===creatures.player.id)}
function currentPlayerHp(){const record=currentPlayerRecord();return Math.max(0,Math.min(Number(record?.maxHp??100),Number(record?.hp??100)))}
function persistPlayerHp(){const record=currentPlayerRecord();if(session?.updateHp&&record)session.updateHp(record.uid||record.id,creatures.player.hp)}
function consumeItemTurn(){if(!state||state.over)return;state.busy=true;render();setTimeout(()=>enemyTurn?.(),battleTurnDelay())}
let scene,camera,renderer,playerMesh,enemyMesh,clock={getElapsedTime:()=>Date.now()/1000},pulse=0;

function setup3D(){scene=new THREE.Scene();scene.fog=new THREE.Fog(0x061221,12,30);camera=new THREE.PerspectiveCamera(42,1,.1,100);camera.position.set(0,5.8,14);camera.lookAt(0,.8,0);renderer=new THREE.WebGLRenderer({canvas:$('battleCanvas'),antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;scene.add(new THREE.HemisphereLight(0x9de8ff,0x06101c,2));const key=new THREE.DirectionalLight(0xffffff,2.4);key.position.set(-5,8,8);scene.add(key);const floor=new THREE.Mesh(new THREE.CircleGeometry(7,64),new THREE.MeshStandardMaterial({color:0x092b40,metalness:.5,roughness:.45,transparent:true,opacity:.8}));floor.rotation.x=-Math.PI/2;floor.position.y=-.05;scene.add(floor);const ring=new THREE.Mesh(new THREE.TorusGeometry(4.5,.025,8,96),new THREE.MeshBasicMaterial({color:0x3bcfff}));ring.rotation.x=Math.PI/2;ring.position.y=.02;scene.add(ring);playerMesh=makeFighter(creatures.player,-3);enemyMesh=makeFighter(creatures.enemy,3);scene.add(playerMesh,enemyMesh);resize();window.addEventListener('resize',resize);if(window.ResizeObserver)new ResizeObserver(resize).observe(arenaView);requestAnimationFrame(loop)}
function makeFighter(data,x){const group=new THREE.Group();group.position.set(x,.55,0);const glow=new THREE.Mesh(new THREE.SphereGeometry(1.45,32,20),new THREE.MeshBasicMaterial({color:data.color,transparent:true,opacity:.06}));group.add(glow);const tex=new THREE.TextureLoader().load(data.sprite,()=>{loadedSprites+=1;if(loadedSprites>=2&&renderer)arenaView.classList.add('sprites-ready')});tex.colorSpace=THREE.SRGBColorSpace;const sprite=new THREE.Mesh(new THREE.PlaneGeometry(2.8,2.8),new THREE.MeshBasicMaterial({map:tex,transparent:true,side:THREE.DoubleSide}));sprite.position.y=.08;sprite.position.z=1;if(x<0)sprite.scale.x=-1;sprite.renderOrder=10;sprite.material.depthTest=false;group.add(sprite);const halo=new THREE.Mesh(new THREE.TorusGeometry(1.48,.035,8,48),new THREE.MeshBasicMaterial({color:data.color,transparent:true,opacity:.75}));halo.rotation.x=Math.PI/2;halo.position.y=-.9;group.add(halo);group.userData={sprite,glow,halo};return group}
function resize(){const box=$('battleCanvas').getBoundingClientRect();if(!box.width||!box.height)return;renderer.setSize(box.width,box.height,false);camera.aspect=box.width/box.height;camera.updateProjectionMatrix();const fit=Math.min(1,Math.max(.58,box.width/560));if(playerMesh){playerMesh.scale.setScalar(fit);playerMesh.position.x=-3*fit}if(enemyMesh){enemyMesh.scale.setScalar(fit);enemyMesh.position.x=3*fit}}
function loop(){const t=clock.getElapsedTime();pulse=t;[playerMesh,enemyMesh].forEach((m,i)=>{m.position.y=.55+Math.sin(t*1.8+i)*.08;m.rotation.y=Math.sin(t*.55+i)*.08;m.userData.halo.rotation.z=t*(i?-.45:.45)});renderer.render(scene,camera);arenaView.classList.add('webgl-ready');requestAnimationFrame(loop)}
function render(){for(const side of ['player','enemy']){const c=creatures[side];const pct=Math.max(0,c.hp/c.maxHp*100);$(side+'Hp').style.width=pct+'%';$(side+'HpText').textContent=`${c.hp} / ${c.maxHp} HP`}$('turnText').textContent=state.over?'BATTLE COMPLETE':state.busy?'ENEMY TURN':'YOUR TURN';$('battleLog').textContent=state.message;if(typeof renderMoves==='function')renderMoves();const sv=$('stabilityValue'),sf=$('stabilityFill');if(sv)sv.textContent=`${state.stability}%`;if(sf)sf.style.width=`${state.stability}%`;document.querySelectorAll('.action').forEach(b=>b.disabled=state.busy||state.over);if(state.over&&creatures.player.hp<=0&&!state.resultShown){state.resultShown=true;setTimeout(()=>showBattleResult('defeat'),0)}}
function activateBattlePlayer(id){const record=session.party?.().find(item=>(item.uid||item.id)===id);if(!record)return false;const source=data.species.find(item=>item.id===record.id)||record;Object.assign(creatures.player,source,record,{sprite:record.sprite||'./data/sprites/'+source.sprite,hp:Math.max(0,Math.min(Number(record.maxHp??100),Number(record.hp??100))),maxHp:Number(record.maxHp??100),stats:record.stats||session.createInstanceStats?.(source)||source.stats||{attack:60,defense:60,speed:60}});renderMoves();if(scene&&playerMesh){scene.remove(playerMesh);playerMesh=makeFighter(creatures.player,-3);scene.add(playerMesh);resize()}return true}
function showBattleResult(kind='defeat'){const modal=$('captureModal')||document.createElement('div');if(!modal.id){modal.id='captureModal';modal.className='capture-modal';document.body.appendChild(modal)}const escaped=kind==='escaped',active=session.starter(),choices=session.party().filter(item=>(item.uid||item.id)!==active&&Number(item.hp??100)>0);if(!escaped&&choices.length){modal.innerHTML=`<div class="capture-card"><span class="eyebrow">SIGNAL LOST</span><h2>Deploy a replacement</h2><p>Your active DataByte fainted. Choose a healthy team member.</p><div class="switch-list">${choices.map(item=>`<button class="ghost" data-replace-key="${item.uid||item.id}">${item.name}<small>${item.hp??100} HP</small></button>`).join('')}</div></div>`;modal.classList.add('is-open');modal.querySelectorAll('[data-replace-key]').forEach(button=>button.addEventListener('click',()=>{const key=button.dataset.replaceKey,record=session.party().find(item=>(item.uid||item.id)===key);if(!record||!activateBattlePlayer(key)||!session.setStarter(key))return;modal.classList.remove('is-open');state.over=false;state.busy=false;state.resultShown=false;state.outcome=null;state.message=`${creatures.player.name} entered the battle.`;render()}));return}modal.innerHTML=`<div class="capture-card"><span class="eyebrow">${escaped?'SIGNAL LOST':'BATTLE OVER'}</span><h2>${escaped?'Encounter escaped':'DataByte fainted'}</h2><p>${escaped?'The signal collapsed before it could be captured.':'Your full team needs Signal Reboot before another battle.'}</p><div class="outcome-actions"><button class="ghost" data-capture-close>RETURN TO SCANNER</button></div></div>`;modal.classList.add('is-open');modal.querySelector('[data-capture-close]')?.addEventListener('click',returnToScanner)}
function statusList(key){return BattleStatus.list(state,key)}
function playerHasStatus(id){return BattleStatus.has(state,'playerStatus',id)}
function enemyHasStatus(id){return BattleStatus.has(state,'enemyStatus',id)}
function statusStacks(key,id){return BattleStatus.stacks(state,key,id)}
function statusMultiplier(key,id,field){return BattleStatus.multiplier(state,key,id,field)}
function consumeStatus(key,id){return BattleStatus.consume(state,key,id)}
function playerAttackMultiplier(){let multiplier=1;for(const id of ['bound','drained','corruption','infected','charged','boost'])multiplier*=statusMultiplier('playerStatus',id,'attackMultiplier');if(playerHasStatus('charged'))consumeStatus('playerStatus','charged');return multiplier}
function playerIncomingMultiplier(){let multiplier=1;for(const id of ['glitched','focused','shield','guarded'])multiplier*=statusMultiplier('playerStatus',id,'damageTakenMultiplier');return multiplier}
function enemyAttackMultiplier(){let multiplier=1;for(const id of ['bound','drained','corruption','infected','charged','boost'])multiplier*=statusMultiplier('enemyStatus',id,'attackMultiplier');if(enemyHasStatus('charged'))consumeStatus('enemyStatus','charged');return multiplier}
function enemyIncomingMultiplier(){let multiplier=1;for(const id of ['glitched','focused','shield','guarded'])multiplier*=statusMultiplier('enemyStatus',id,'damageTakenMultiplier');return multiplier}
function playerSpeed(){let multiplier=1;for(const id of ['bound','shock','freeze','boost'])multiplier*=statusMultiplier('playerStatus',id,'speedMultiplier');return Math.max(20,Math.round((Number(creatures.player.stats?.speed)||60)*multiplier))}
function effectiveMoveAccuracy(move,key){const base=Math.min(100,Math.max(1,Number(move?.accuracy??100)||100)),debuffed=BattleStatus.has(state,key,'shock')||BattleStatus.has(state,key,'misdirected');if(base>=100&&!debuffed)return 100;return Math.min(100,Math.max(1,base*statusMultiplier(key,'shock','accuracyMultiplier')*statusMultiplier(key,'misdirected','accuracyMultiplier')))}
function playerMoveAccuracy(move){return effectiveMoveAccuracy(move,'playerStatus')}
function enemyMoveAccuracy(move){return effectiveMoveAccuracy(move,'enemyStatus')}
function enemySpeed(){let multiplier=1;for(const id of ['bound','shock','freeze','boost'])multiplier*=statusMultiplier('enemyStatus',id,'speedMultiplier');return Math.max(20,Math.round((Number(creatures.enemy.stats?.speed)||60)*multiplier))}
function battleTurnDelay(){return Math.max(750,1450-Math.max(playerSpeed(),enemySpeed())*4)}
function showRewardScreen(kind){if(!state||state.rewardGranted)return;const modal=$('captureModal');if(!modal)return;state.rewardGranted=true;modal.classList.add('is-open');const captured=kind==='captured',reward=window.DataByteBattleRewards?.settle?.(state,captured?'captured':'defeat')||{xp:0,bonusXp:0,coins:0,item:''},baseXp=Number(reward.xp||0)-Number(reward.bonusXp||0),bonusXp=Number(reward.bonusXp||0),party=session.party?.()||[],active=session.starter?.(),lead=party.find(item=>(item.uid||item.id)===active||item.id===active)||party[0],leadName=lead?.name||creatures.player.name,itemNames={patch:'Repair Patch',repair:'Repair Pulse',boost:'Signal Boost'};if(captured){modal.innerHTML=`<div class="capture-card"><span class="eyebrow">BATTLE REWARDS</span><h2>${creatures.enemy.name} captured</h2><p>+${baseXp} battle XP and +${bonusXp} capture bonus XP to ${leadName}. Signal added to your ${session.party().length>=5?'repository':'party'}.</p><button class="scan-button" data-capture-close>CONTINUE SCANNING</button></div>`}else{modal.innerHTML=`<div class="capture-card"><span class="eyebrow">BATTLE REWARDS</span><h2>Signal secured</h2><p>+${baseXp} battle XP to ${leadName}. +${reward.coins||0} DataByteCoin. Item found: ${itemNames[reward.item]||'Field Item'}.</p><button class="ghost" data-capture-close>RETURN TO SCANNER</button></div>`}modal.querySelector('[data-capture-close]')?.addEventListener('click',returnToScanner)}
function showEscapeScreen(){if(!state)return;const modal=$('captureModal');if(!modal)return;state.resultShown=true;modal.innerHTML=`<div class="capture-card"><span class="eyebrow">SIGNAL LOST</span><h2>${creatures.enemy.name} escaped</h2><p>The signal destabilized after repeated failed captures. Return to the scanner and try a new encounter.</p><button class="scan-button" data-capture-close>RETURN TO SCANNER</button></div>`;modal.classList.add('is-open');modal.querySelector('[data-capture-close]')?.addEventListener('click',returnToScanner)}
function captureChance(){const caps={Starter:100,Common:85,Uncommon:76,Rare:66,Epic:56,Legendary:46,Mythic:36},authored=Number(creatures.enemy?.captureChance),cap=Number.isFinite(authored)&&authored>0?authored:(caps[creatures.enemy?.rarity]??76),level=Math.max(1,Number(creatures.enemy?.level)||1),stage=window.DataByteProgressionData?.stageFor?.(creatures.enemy)||Number(creatures.enemy?.evolutionStage)||1,levelPenalty=Math.floor(level/10),stagePenalty=(stage-1)*5,pressure=Math.min(35,state?.capturePressure||0),stability=Math.max(0,state?.stability??100),maxStability=Math.max(1,Number(state?.maxStability||100)),healthBonus=Math.max(0,Math.min(25,(1-(Number(creatures.enemy?.hp)||0)/Math.max(1,Number(creatures.enemy?.maxHp)||100))*25));return Math.max(5,Math.min(95,Math.round(cap+healthBonus+pressure-levelPenalty-stagePenalty-(maxStability-stability)*3)))}
function saveParty(){const chance=captureChance(),stability=Math.max(0,state?.stability??100),pressure=Math.min(45,state?.capturePressure||0),coins=session.coins?.()??0;if(coins<1){setTimeout(()=>showOutcome('battle'),40);return {ok:false,reason:'no-coins',chance,coins}};if(!session.spendCoin?.()){setTimeout(()=>showOutcome('battle'),40);return {ok:false,reason:'no-coins',chance,coins:0};}if(Math.random()*100>=chance){state.stability=Math.max(0,stability-15);state.capturePressure=Math.max(0,pressure-5);if(!state.stability)setTimeout(showEscapeScreen,40);return {ok:false,reason:state.stability?'signal-broke-free':'signal-collapsed',chance,coins:session.coins?.(),stability:state.stability}}const result=session.capture(creatures.enemy);if(result.ok){state.captureLocation=result.location||'party';session.markCaptured?.(creatures.enemy.id);setTimeout(()=>showRewardScreen('captured'),40)}return {...result,chance,coins:session.coins?.(),stability:state.stability}}
function renderParty(){const list=$('partyList');if(!list)return;const active=session.starter(),party=session.party(),repo=session.repository();list.innerHTML=(party.length?party.map(p=>`<button class="party-card ${p.id===active?'is-lead':''}" data-lead="${p.id}" data-select-state="0"><img src="${p.sprite}" alt=""><span><b>${p.name}</b><small>${p.id===active?'Active lead':'Tap to select'}</small></span></button>`).join(''):'<span class="party-empty">No active DataBytes yet.</span>')+(repo.length?`<span class="repository-label">Repository (${repo.length})</span>`+repo.map(p=>`<button class="party-card" data-repo="${p.id}"><img src="${p.sprite}" alt=""><span><b>${p.name}</b><small>Stored signal · tap to swap</small></span></button>`).join(''):'');list.querySelectorAll('[data-lead]').forEach(button=>button.addEventListener('click',()=>{const state=Number(button.dataset.selectState||0)+1;button.dataset.selectState=state>2?'0':String(state);button.classList.toggle('is-selected',state===1);button.classList.toggle('is-storage-ready',state===2);button.querySelector('small').textContent=state===1?'Lead selected':state===2?'Tap again to store':'Tap to select';if(state===1){session.setLead(button.dataset.lead);$('playerName').textContent=button.querySelector('b').textContent.toUpperCase()}else if(state===2){session.store(button.dataset.lead);renderParty()}}));list.querySelectorAll('[data-repo]').forEach(button=>button.addEventListener('click',()=>session.deploy(button.dataset.repo)))}
function renderDex(){$('dexSeenCount').textContent=session.seen().length;$('dexCapturedCount').textContent=session.party().concat(session.repository()).length}
function stopActiveScan(){if(scanTimer){clearInterval(scanTimer);scanTimer=null}if(scanHandoffTimer){clearTimeout(scanHandoffTimer);scanHandoffTimer=null}$('scannerView')?.classList.remove('is-scanning');$('scanBtn').disabled=false;$('scanProgress').style.width='0%'}
function returnToScanner(){stopActiveScan();const box=$('battleOutcome');box?.classList.add('hidden');$('captureModal')?.classList.remove('is-open');$('controlView').classList.add('hidden');$('arenaView').classList.add('hidden');$('encounterView').classList.add('hidden');$('encounterView').dataset.seen='';$('scannerView').classList.remove('hidden');$('scannerStatus').textContent='No active signal locked. Start a scan to discover a DataByte.'}
function showOutcome(mode='battle'){const box=$('battleOutcome');if(!box)return;box.classList.add('hidden');let modal=$('captureModal');if(!modal){modal=document.createElement('div');modal.id='captureModal';modal.className='capture-modal';document.body.appendChild(modal)}const open=(content)=>{modal.innerHTML=content;modal.classList.add('is-open');modal.querySelector('[data-capture-close]')?.addEventListener('click',()=>{if(mode==='battle'&&state.over&&!state.rewardGranted)showRewardScreen('defeat');else returnToScanner()})};const label=mode==='discovery'?'SIGNAL LOCKED':'SIGNAL DESTABILIZED';const noCoins=(session.coins?.()??0)<1;const copy=noCoins?'No DataByteCoins remain. Return to the scanner for another signal.':mode==='discovery'?'The signal is readable. Throw a DataByteCoin to attempt capture.':'Throw a DataByteCoin to capture this signal.';const actions=noCoins?'<button class="ghost" data-capture-close>RETURN TO SCANNER</button>':'<button id="captureWinBtn" class="scan-button">CAPTURE SIGNAL</button><button class="ghost" data-capture-close>CONTINUE SCANNING</button>';open(`<div class="capture-card"><span class="eyebrow">${label}</span><h2>${creatures.enemy.name}</h2><p>${copy}</p><div class="outcome-actions">${actions}</div></div>`);if(noCoins)return;$('captureWinBtn').onclick=modal._captureAttempt=()=>{modal.classList.remove('is-open');$('arenaView').classList.add('capture-active');setTimeout(()=>{const result=saveParty();$('arenaView').classList.remove('capture-active');if(result.ok){open(`<div class="capture-card"><span class="eyebrow">SIGNAL STORED</span><h2>${creatures.enemy.name} captured</h2><p>Your party storage has been updated.</p><button class="scan-button" data-capture-close>CONTINUE SCANNING</button></div>`);state.message=`${creatures.enemy.name} joined your party.`;render();return}state.message=`${creatures.enemy.name} broke free.`;if(mode==='battle'&&!state.over&&Number(result.stability??1)>0){modal.classList.remove('is-open');state.busy=true;render();setTimeout(canonicalEnemyTurn,battleTurnDelay());return}open(`<div class="capture-card"><span class="eyebrow">CAPTURE FAILED</span><h2>${creatures.enemy.name} broke free</h2><p>Try the capture again while the signal is unstable.</p><div class="outcome-actions"><button id="captureRetryBtn" class="scan-button">TRY AGAIN</button><button class="ghost" data-capture-close>CONTINUE SCANNING</button></div></div>`);$('captureRetryBtn').onclick=()=>{modal._captureAttempt?.()};render()},650)} }
function beginScan(){if(scanTimer||scanHandoffTimer)return;try{reset()}catch(error){console.error('Could not prepare a new encounter.',error);stopActiveScan();scannerStatus.textContent='Signal reset failed. Choose a region again, then retry the scan.';return}scannerView.classList.add('is-scanning');const button=scanBtn;const progress=scanProgress;button.disabled=true;let value=0;scanTimer=setInterval(()=>{value+=20;progress.style.width=value+'%';scannerStatus.textContent=value<100?'Scanning signal layer '+value+'%':'Signal locked: discovery ready.';if(value>=100){clearInterval(scanTimer);scanTimer=null;scannerStatus.textContent='Signal locked. Opening discovery record...';scanHandoffTimer=setTimeout(()=>{scanHandoffTimer=null;session.markSeen?.(creatures.enemy);scannerView.classList.remove('is-scanning');scannerView.classList.add('hidden');arenaView.classList.add('hidden');controlView.classList.add('hidden');encounterView.classList.remove('hidden');encounterView.dataset.seen='true';window.dispatchEvent(new CustomEvent('databyte:encounter-ready'))},900)}},180)} function start(){window.addEventListener('databyte:party-updated',()=>{const active=session.starter(),lead=session.party().find(p=>(p.uid||p.id)===active||p.id===active);if(lead){playerName.textContent=lead.name.toUpperCase();if(scene&&playerMesh){scene.remove(playerMesh);const source=data.species.find(s=>s.id===lead.id)||lead;playerMesh=makeFighter({...source,sprite:lead.sprite},-3);scene.add(playerMesh);resize()}}});$('scanBtn').addEventListener('click',beginScan);try{setup3D()}catch(error){console.warn('Three.js presentation unavailable; continuing with DOM battle UI.',error)}$('actions').innerHTML=moves.map((m,i)=>`<button class="action" data-move="${i}"><b>${m.name}</b><span>${m.copy} · ${m.power<0?'+'+(-m.power)+' HP':m.power+' DMG'}</span></button>`).join('');$('actions').addEventListener('click',e=>{const b=e.target.closest('.action');if(b)act(moves[Number(b.dataset.move)])});$('resetBtn').addEventListener('click',reset);renderDex();reset()}
reset=canonicalReset;act=canonicalBattleAct;enemyTurn=canonicalEnemyTurn;start(); renderMoves(); window.DataByteBattle.creatures=creatures; window.DataByteBattle.capture=saveParty; window.DataByteBattle.captureChance=captureChance; window.DataByteBattle.showCapturePrompt=(mode='discovery')=>showOutcome(mode);
window.addEventListener('databyte:deploy-requested',()=>{if(state)state.resultShown=false});
window.addEventListener('databyte:starter-updated',()=>{if(state)state.resultShown=false});
function battlePlayerFainted(){if(!state||state.resultShown)return;state.outcome='defeat';state.over=true;state.busy=false;state.resultShown=true;state.message='Your DataByte lost signal.';render();showBattleResult('defeat')}
function battleEnemyFainted(){if(!state||state.resultShown)return;state.outcome='victory';state.over=true;state.busy=false;state.resultShown=true;const reward=window.DataByteBattleRewards?.settleVictory?.(state)||{xp:0};state.message=`${creatures.enemy.name} dissolved into clean data. Victory! +${reward.xp||0} XP secured.`;render();setTimeout(()=>showOutcome(),0)}
window.DataByteBattle.playerFainted=battlePlayerFainted;
window.DataByteBattle.enemyFainted=battleEnemyFainted;
function canonicalEnemyTurn(){if(!state||state.over)return;state.busy=true;render();setTimeout(()=>{if(state.over)return;const profile=enemyProfile(creatures.enemy.alignment),fallback=mapMove({id:'alignment-strike',name:profile.move,moveType:'attack',configuration:'Signal',power:Math.round((profile.min+profile.max)/2),accuracy:100,statusEffect:{id:profile.status,chance:Math.round(profile.glitch*100),durationTurns:2},description:'An alignment-driven signal strike.'}),move=chooseEnemyMove({enemy:creatures.enemy,moves:resolveMoves(creatures.enemy.id)})||fallback,freezeChance=Number(window.DataByteStatusRuntime?.definition?.('freeze')?.actionBlockChance)||0;if(enemyHasStatus('freeze')&&Math.random()*100<freezeChance){state.message=`${creatures.enemy.name} is frozen and cannot act.`;state.busy=false;render();return}const accuracy=enemyMoveAccuracy(move),hit=accuracy>=100||Math.random()*100<accuracy;let attemptedAttack=false;if(!hit){state.message=`${creatures.enemy.name}'s ${move.name} missed.`}else if(move.power===0){const heal=Math.max(8,Math.round(creatures.enemy.maxHp*.12)),before=creatures.enemy.hp;creatures.enemy.hp=Math.min(creatures.enemy.maxHp,creatures.enemy.hp+heal);window.DataByteMoveEffects?.apply?.(move,'enemy');state.message=`${creatures.enemy.name} used ${move.name} and recovered ${creatures.enemy.hp-before} HP.`}else{attemptedAttack=true;const enemyStats=creatures.enemy.stats||session.createInstanceStats?.(creatures.enemy)||{attack:60,defense:60,speed:60,crit:0},critical=Math.random()*100<Math.max(0,Number(enemyStats.crit)||0),damage=enemyDamage({raw:move.power,move:{...move,defenderAlignment:creatures.player.alignment},attack:enemyStats.attack,defense:creatures.player.stats?.defense,attackerLevel:creatures.enemy.level,defenderLevel:creatures.player.level,incomingMultiplier:playerIncomingMultiplier(),attackMultiplier:enemyAttackMultiplier(),leak:playerHasStatus('glitched')?4:0,critical});creatures.player.hp=Math.max(0,creatures.player.hp-damage);persistPlayerHp();if(creatures.player.hp>0)window.DataByteMoveEffects?.apply?.(move,'enemy');state.message=`${creatures.enemy.name} used ${move.name} for ${damage}${critical?' CRITICAL':''} damage.`}state.stability=Math.max(0,state.stability-(attemptedAttack?(state.guarding?2:profile.drain):2));state.guarding=false;const tick=window.DataByteMoveEffects?.tickTurnEnd?.('enemyStatus');if(tick?.defeated)return;state.busy=false;if(!state.stability){state.over=true;state.resultShown=false;showEscapeScreen();return}if(!creatures.player.hp){battlePlayerFainted();return}render()},battleTurnDelay())}
function canonicalBattleAct(move){if(state.busy||state.over||!move)return;state.busy=true;const freezeChance=Number(window.DataByteStatusRuntime?.definition?.('freeze')?.actionBlockChance)||0;if(playerHasStatus('freeze')&&Math.random()*100<freezeChance){state.message=`${creatures.player.name} is frozen and cannot act.`;render();return setTimeout(canonicalEnemyTurn,battleTurnDelay())}const accuracy=playerMoveAccuracy(move),hit=accuracy>=100||Math.random()*100<accuracy;if(!hit){state.message=`${creatures.player.name}'s ${move.name} missed.`}else if(move.power===0){const heal=Math.max(8,Math.round(creatures.player.maxHp*.12)),before=creatures.player.hp;creatures.player.hp=Math.min(creatures.player.maxHp,creatures.player.hp+heal);persistPlayerHp();state.stability=Math.min(100,state.stability+8);window.DataByteMoveEffects?.apply?.(move,'player');state.message=`${creatures.player.name} used ${move.name} and recovered ${creatures.player.hp-before} HP.`}else{const attack=Math.max(1,Number(creatures.player.stats?.attack)||60),defense=Math.max(1,Number(creatures.enemy.stats?.defense)||60),critChance=Math.max(0,Number(creatures.player.stats?.crit)||0),critical=Math.random()*100<critChance,damage=playerDamage({move:{...move,defenderAlignment:creatures.enemy.alignment},attack,defense,attackerLevel:creatures.player.level,defenderLevel:creatures.enemy.level,attackMultiplier:playerAttackMultiplier(),incomingMultiplier:enemyIncomingMultiplier(),critical});creatures.enemy.hp=Math.max(0,creatures.enemy.hp-damage);state.stability=Math.min(100,state.stability+3);if(creatures.enemy.hp>0)window.DataByteMoveEffects?.apply?.(move,'player');state.message=`${creatures.player.name} used ${move.name} for ${damage}${critical?' CRITICAL':''} damage.`}const tick=window.DataByteMoveEffects?.tickTurnEnd?.('playerStatus');if(tick?.defeated)return;if(!creatures.enemy.hp){battleEnemyFainted();return}state.busy=true;render();setTimeout(canonicalEnemyTurn,battleTurnDelay())}
act=canonicalBattleAct;enemyTurn=canonicalEnemyTurn;
function canonicalReset(){const active=session.starter();if(active)activateBattlePlayer(active);const next=session.createEncounter(creatures.player.id,creatures.enemy.id),wild=session.createWildInstance?.(next)||{...next,hp:100,maxHp:100,stats:next.stats||session.createInstanceStats?.(next)||{attack:60,defense:60,speed:60}},maxStability=Math.max(1,Number(next.maxStability||100));Object.assign(creatures.enemy,{...next,...wild,name:/pending/i.test(next.name||'')?'Unknown Signal':next.name,sprite:'./data/sprites/'+next.sprite,hp:wild.maxHp,maxHp:wild.maxHp,stats:wild.stats||next.stats||{attack:60,defense:60,speed:60}});if(scene&&enemyMesh){scene.remove(enemyMesh);enemyMesh=makeFighter(creatures.enemy,3);scene.add(enemyMesh);resize()}$('enemyName').textContent=creatures.enemy.name.toUpperCase();$('playerName').textContent=creatures.player.name.toUpperCase();creatures.player.hp=currentPlayerHp();const outcome=$('battleOutcome');if(outcome)outcome.classList.add('hidden');state=createBattleState({maxStability,message:`A wild ${creatures.enemy.name} entered the arena.`});render();if(creatures.player.hp<=0)battlePlayerFainted()}
function canonicalSwitchTurn(){if(!state||state.busy||state.over)return false;clearPlayerBattleEffects(state);state.busy=true;state.message=`${creatures.player.name} entered the battle.`;render();setTimeout(canonicalEnemyTurn,battleTurnDelay());return true}
render=()=>renderBattleView({state,creatures,getElement:$});reset=canonicalReset;window.DataByteBattle.switchTurn=canonicalSwitchTurn;canonicalReset();
window.addEventListener('databyte:region-updated',()=>{stopActiveScan();$('captureModal')?.classList.remove('is-open');$('encounterView')?.classList.add('hidden');$('arenaView')?.classList.add('hidden');$('controlView')?.classList.add('hidden');$('scannerView')?.classList.remove('hidden');try{canonicalReset();$('scannerStatus').textContent=`Region synchronized: ${window.DataByteRegions?.current?.().name||'new zone'}. Start a scan when ready.`}catch(error){console.error('Could not synchronize region encounter.',error);$('scannerStatus').textContent='Region changed, but the encounter could not reset. Select the region again and retry.'}});
function guardZeroHpScan(event){if(currentPlayerHp()>0)return;event.preventDefault();event.stopImmediatePropagation();$('scannerStatus').textContent='Your active DataByte has no signal. Use SIGNAL REBOOT before scanning.';$('scanBtn').disabled=false;const reboot=$('signalRebootBtn');if(reboot){reboot.classList.remove('reboot-attention');void reboot.offsetWidth;reboot.classList.add('reboot-attention');setTimeout(()=>reboot.classList.remove('reboot-attention'),1800)}}
$('scanBtn')?.addEventListener('click',guardZeroHpScan,true);
renderMoves=()=>{moves=resolveMoves(creatures.player.id);$('actions').innerHTML=moves.map((m,i)=>`<button class="action" data-move="${i}"><b>${m.name}</b><span>${m.copy} · ${m.power<0?'+'+(-m.power)+' HP':m.power+' DMG'} · ACC ${Math.round(playerMoveAccuracy(m))}%</span></button>`).join('')};
renderMoves();
window.addEventListener('databyte:party-updated',()=>{
  const active=session?.starter?.();
  const next=session?.party?.().find(item=>(item.uid||item.id)===active||item.id===active);
  if(!next)return;
  Object.assign(creatures.player,next,{hp:Math.max(0,Math.min(Number(next.maxHp??100),Number(next.hp??100))),maxHp:Number(next.maxHp??100)});
  renderMoves();
  if(state)render();
});
