import * as THREE from './vendor/three.module.js';
let loadedSprites=0;
const data=window.THREE_BATTLE_DATA||{moves:[],species:[]}; const starterId=localStorage.getItem('vl_three_battle_starter'); const starterAliases={kindlekid:{id:'kindlekid',name:'KindleKid',sprite:'placeholder.png',color:0xff9f43},coincalf:{id:'coincalf',name:'CoinCalf',sprite:'placeholder.png',color:0xffd166},gemneye:{id:'gemneye',name:'Gem-N-Eye',sprite:'placeholder.png',color:0xc084fc},sixela:{id:'sixela',name:'6.ela',sprite:'placeholder.png',color:0x8bd450},pixelpup:{id:'pixelpup',name:'PixelPup',sprite:'placeholder.png',color:0x60a5fa},centaurcher:{id:'centaurcher',name:'Centaurcher',sprite:'placeholder.png',color:0xd97706},clockadile:{id:'clockadile',name:'Clockadile',sprite:'placeholder.png',color:0x84cc16},aquobit:{id:'aquobit',name:'AquoBit',sprite:'placeholder.png',color:0x22d3ee}}; const ps=data.species.find(s=>s.id===starterId)||starterAliases[starterId]||data.species[0]||{name:'Leovolt',sprite:'leovolt.png',color:0x45d8ff}; const encounterPool=data.species.filter(s=>s.id!=='placeholder'&&!/pending/i.test(s.name||'')); const es=encounterPool[Math.floor(Math.random()*Math.max(1,encounterPool.length))]||{id:'scorpyone',name:'Scorpyone',sprite:'scorpyone.png',color:0xff6689}; const creatures={player:{...ps,sprite:'./data/sprites/'+ps.sprite,hp:100,maxHp:100},enemy:{...es,sprite:'./data/sprites/'+es.sprite,hp:100,maxHp:100}};
if(/pending/i.test(creatures.enemy.name||''))creatures.enemy.name='Unknown Signal';
const session=window.DataByteSession; const moves=data.moves.map(m=>({name:m.name,power:m.power,accuracy:m.accuracy,downloadEffect:m.downloadEffect,copy:m.description}));
const $=id=>document.getElementById(id); let state;
let scene,camera,renderer,playerMesh,enemyMesh,clock={getElapsedTime:()=>Date.now()/1000},pulse=0;

function setup3D(){scene=new THREE.Scene();scene.fog=new THREE.Fog(0x061221,12,30);camera=new THREE.PerspectiveCamera(42,1,.1,100);camera.position.set(0,5.8,14);camera.lookAt(0,.8,0);renderer=new THREE.WebGLRenderer({canvas:$('battleCanvas'),antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;scene.add(new THREE.HemisphereLight(0x9de8ff,0x06101c,2));const key=new THREE.DirectionalLight(0xffffff,2.4);key.position.set(-5,8,8);scene.add(key);const floor=new THREE.Mesh(new THREE.CircleGeometry(7,64),new THREE.MeshStandardMaterial({color:0x092b40,metalness:.5,roughness:.45,transparent:true,opacity:.8}));floor.rotation.x=-Math.PI/2;floor.position.y=-.05;scene.add(floor);const ring=new THREE.Mesh(new THREE.TorusGeometry(4.5,.025,8,96),new THREE.MeshBasicMaterial({color:0x3bcfff}));ring.rotation.x=Math.PI/2;ring.position.y=.02;scene.add(ring);playerMesh=makeFighter(creatures.player,-3);enemyMesh=makeFighter(creatures.enemy,3);scene.add(playerMesh,enemyMesh);resize();window.addEventListener('resize',resize);if(window.ResizeObserver)new ResizeObserver(resize).observe(arenaView);requestAnimationFrame(loop)}
function makeFighter(data,x){const group=new THREE.Group();group.position.set(x,.55,0);const glow=new THREE.Mesh(new THREE.SphereGeometry(1.45,32,20),new THREE.MeshBasicMaterial({color:data.color,transparent:true,opacity:.06}));group.add(glow);const tex=new THREE.TextureLoader().load(data.sprite,()=>{loadedSprites+=1;if(loadedSprites>=2&&renderer)arenaView.classList.add('sprites-ready')});tex.colorSpace=THREE.SRGBColorSpace;const sprite=new THREE.Mesh(new THREE.PlaneGeometry(2.8,2.8),new THREE.MeshBasicMaterial({map:tex,transparent:true,side:THREE.DoubleSide}));sprite.position.y=.08;sprite.position.z=1;if(x<0)sprite.scale.x=-1;sprite.renderOrder=10;sprite.material.depthTest=false;group.add(sprite);const halo=new THREE.Mesh(new THREE.TorusGeometry(1.48,.035,8,48),new THREE.MeshBasicMaterial({color:data.color,transparent:true,opacity:.75}));halo.rotation.x=Math.PI/2;halo.position.y=-.9;group.add(halo);group.userData={sprite,glow,halo};return group}
function resize(){const box=$('battleCanvas').getBoundingClientRect();if(!box.width||!box.height)return;renderer.setSize(box.width,box.height,false);camera.aspect=box.width/box.height;camera.updateProjectionMatrix();const fit=Math.min(1,Math.max(.58,box.width/560));if(playerMesh){playerMesh.scale.setScalar(fit);playerMesh.position.x=-3*fit}if(enemyMesh){enemyMesh.scale.setScalar(fit);enemyMesh.position.x=3*fit}}
function loop(){const t=clock.getElapsedTime();pulse=t;[playerMesh,enemyMesh].forEach((m,i)=>{m.position.y=.55+Math.sin(t*1.8+i)*.08;m.rotation.y=Math.sin(t*.55+i)*.08;m.userData.halo.rotation.z=t*(i?-.45:.45)});renderer.render(scene,camera);arenaView.classList.add('webgl-ready');requestAnimationFrame(loop)}
function render(){for(const side of ['player','enemy']){const c=creatures[side];const pct=Math.max(0,c.hp/c.maxHp*100);$(side+'Hp').style.width=pct+'%';$(side+'HpText').textContent=`${c.hp} / ${c.maxHp} HP`}$('turnText').textContent=state.over?'BATTLE COMPLETE':state.busy?'ENEMY TURN':'YOUR TURN';$('battleLog').textContent=state.message;document.querySelectorAll('.action').forEach(b=>b.disabled=state.busy||state.over)}
function enemyTurn(){state.busy=true;render();setTimeout(()=>{const damage=10+Math.floor(Math.random()*9);creatures.player.hp=Math.max(0,creatures.player.hp-damage);state.message=`${creatures.enemy.name} countered with Venom Packet for ${damage} damage.`;state.busy=false;if(!creatures.player.hp){state.over=true;state.message='Your DataByte lost signal. Reset to run it again.'}render()},700)}
function saveParty(){const result=session.capture(creatures.enemy);renderParty();return result}
function renderParty(){const list=$('partyList');if(!list)return;const active=session.starter(),party=session.party(),repo=session.repository();list.innerHTML=(party.length?party.map(p=>`<button class="party-card ${p.id===active?'is-lead':''}" data-lead="${p.id}" data-select-state="0"><img src="${p.sprite}" alt=""><span><b>${p.name}</b><small>${p.id===active?'Active lead':'Tap to select'}</small></span></button>`).join(''):'<span class="party-empty">No active DataBytes yet.</span>')+(repo.length?`<span class="repository-label">Repository (${repo.length})</span>`+repo.map(p=>`<button class="party-card" data-repo="${p.id}"><img src="${p.sprite}" alt=""><span><b>${p.name}</b><small>Stored signal · tap to swap</small></span></button>`).join(''):'');list.querySelectorAll('[data-lead]').forEach(button=>button.addEventListener('click',()=>{const state=Number(button.dataset.selectState||0)+1;button.dataset.selectState=state>2?'0':String(state);button.classList.toggle('is-selected',state===1);button.classList.toggle('is-storage-ready',state===2);button.querySelector('small').textContent=state===1?'Lead selected':state===2?'Tap again to store':'Tap to select';if(state===1){session.setLead(button.dataset.lead);$('playerName').textContent=button.querySelector('b').textContent.toUpperCase()}else if(state===2){session.store(button.dataset.lead);renderParty()}}));list.querySelectorAll('[data-repo]').forEach(button=>button.addEventListener('click',()=>session.deploy(button.dataset.repo)))}
function renderDex(){$('dexSeenCount').textContent=session.seen().length;$('dexCapturedCount').textContent=session.party().length}
function returnToScanner(){const box=$('battleOutcome');box?.classList.add('hidden');$('controlView').classList.add('hidden');$('arenaView').classList.add('hidden');$('encounterView').classList.add('hidden');$('encounterView').dataset.seen='';$('scannerView').classList.remove('hidden');$('scanBtn').disabled=false;$('scanProgress').style.width='0%';$('scannerStatus').textContent='No active signal locked. Start a scan to discover a DataByte.'}
function showOutcome(){const box=$('battleOutcome');if(!box)return;box.classList.remove('hidden');box.innerHTML=`<strong>${creatures.enemy.name} destabilized.</strong><span>Capture this signal and add it to your party storage.</span><div class="outcome-actions"><button id="captureWinBtn" class="scan-button">CAPTURE SIGNAL</button><button id="returnScanBtn" class="ghost">CONTINUE SCANNING</button></div>`;$('captureWinBtn').onclick=()=>{saveParty();box.innerHTML=`<strong>${creatures.enemy.name} captured.</strong><span>Your party storage has been updated.</span><button id="returnScanBtn" class="scan-button">CONTINUE SCANNING</button>`;$('returnScanBtn').onclick=returnToScanner;state.message=`${creatures.enemy.name} joined your party.`;render()};$('returnScanBtn').onclick=returnToScanner}
function act(move){if(state.busy||state.over)return;state.busy=true;let amount=move.power;if(amount<0){creatures.player.hp=Math.min(creatures.player.maxHp,creatures.player.hp-amount);state.message=`${creatures.player.name} stabilized ${-amount} signal.`}else{creatures.enemy.hp=Math.max(0,creatures.enemy.hp-amount);state.message=`${creatures.player.name} used ${move.name} for ${amount} damage.`}if(!creatures.enemy.hp){state.over=true;state.busy=false;state.message=`${creatures.enemy.name} dissolved into clean data. Victory!`;showOutcome()}render();if(!state.over)setTimeout(enemyTurn,550)}
function reset(){const next=session.createEncounter(creatures.player.id,creatures.enemy.id);Object.assign(creatures.enemy,{...next,name:/pending/i.test(next.name||'')?'Unknown Signal':next.name,sprite:'./data/sprites/'+next.sprite,hp:100,maxHp:100});if(scene&&enemyMesh){scene.remove(enemyMesh);enemyMesh=makeFighter(creatures.enemy,3);scene.add(enemyMesh);resize()}$('enemyName').textContent=creatures.enemy.name.toUpperCase();$('playerName').textContent=creatures.player.name.toUpperCase();creatures.player.hp=100;const outcome=$('battleOutcome');if(outcome)outcome.classList.add('hidden');state={busy:false,over:false,message:`A wild ${creatures.enemy.name} entered the arena.`};render()}
function beginScan(){reset();const button=scanBtn;const progress=scanProgress;button.disabled=true;let value=0;const timer=setInterval(()=>{value+=20;progress.style.width=value+'%';scannerStatus.textContent=value<100?'Scanning signal layer '+value+'%':'Signal locked: Scorpyone detected.';if(value>=100){clearInterval(timer);scannerStatus.textContent='Signal locked. Loading arena visuals...';setTimeout(()=>{scannerView.classList.add('hidden');arenaView.classList.remove('hidden');controlView.classList.remove('hidden');resize()},900)}},180)} function start(){window.renderParty=renderParty;window.addEventListener('databyte:party-updated',()=>{const lead=session.party().find(p=>p.id===session.starter());if(lead){playerName.textContent=lead.name.toUpperCase();if(scene&&playerMesh){scene.remove(playerMesh);const source=data.species.find(s=>s.id===lead.id)||lead;playerMesh=makeFighter({...source,sprite:lead.sprite},-3);scene.add(playerMesh);resize()}}});$('scanBtn').addEventListener('click',beginScan);try{setup3D()}catch(error){console.warn('Three.js presentation unavailable; continuing with DOM battle UI.',error)}$('actions').innerHTML=moves.map((m,i)=>`<button class="action" data-move="${i}"><b>${m.name}</b><span>${m.copy} · ${m.power<0?'+'+(-m.power)+' HP':m.power+' DMG'}</span></button>`).join('');$('actions').addEventListener('click',e=>{const b=e.target.closest('.action');if(b)act(moves[Number(b.dataset.move)])});$('resetBtn').addEventListener('click',reset);renderParty();renderDex();reset()}
start();
