(function(){
  const PARTY_KEY='vl_three_battle_party',SLOTS_KEY='vl_three_battle_slots',REPO_KEY='vl_three_battle_repository',SEEN_KEY='vl_three_battle_seen',DEX_KEY='vl_three_battle_dex',COIN_KEY='vl_three_battle_coins',MISSION_KEY='vl_three_battle_missions';
  function profileKey(name){return name.startsWith('vl_three_battle_')?name:`vl_three_battle_${name}`}
  function profileGet(name,fallback=null){try{const raw=localStorage.getItem(profileKey(name));return raw===null?fallback:JSON.parse(raw)}catch{return fallback}}
  function profileSet(name,value){localStorage.setItem(profileKey(name),JSON.stringify(value));return value}
  function profileRemove(name){localStorage.removeItem(profileKey(name))}
  function spriteProgress(item){const xp=Math.max(0,Number(item?.xp)||0),level=Math.min(100,Math.floor(xp/100)+1);return {xp,level,nextXp:level<100?level*100:null}}
  function addSpriteXp(id,amount){const gain=Math.max(0,Number(amount)||0);if(!gain)return {ok:false,reason:'invalid-xp'};const collections=[party(),repository()];const item=collections.flat().find(entry=>entry?.id===id);if(!item)return {ok:false,reason:'not-found'};const before=spriteProgress(item);item.xp=before.xp+gain;item.level=spriteProgress(item).level;localStorage.setItem(PARTY_KEY,JSON.stringify(collections[0]));localStorage.setItem(REPO_KEY,JSON.stringify(collections[1]));window.dispatchEvent(new CustomEvent('databyte:party-updated',{detail:{id,xp:item.xp,level:item.level}}));return {ok:true,id,xp:item.xp,level:item.level,previousLevel:before.level,leveledUp:item.level>before.level}}
  function mission(){return profileGet(MISSION_KEY,{survey:0,rewarded:false})}
  function coins(){const value=Number(localStorage.getItem(COIN_KEY));if(!Number.isFinite(value)){localStorage.setItem(COIN_KEY,'3');return 3}return value}
  function addCoins(amount){const next=Math.max(0,coins()+amount);localStorage.setItem(COIN_KEY,String(next));window.dispatchEvent(new CustomEvent('databyte:coins-updated',{detail:{coins:next}}));return next}
  function spendCoin(){if(coins()<1)return false;addCoins(-1);return true}
  function roster(){return (window.THREE_BATTLE_DATA?.species||[]).filter(s=>s.id!=='placeholder');}
  function seen(){try{return JSON.parse(localStorage.getItem(SEEN_KEY)||'[]')}catch{return[]}}
  function dex(){try{return JSON.parse(localStorage.getItem(DEX_KEY)||'[]')}catch{return[]}}
  function markSeen(sprite){const items=seen();if(!items.includes(sprite.id)){items.push(sprite.id);localStorage.setItem(SEEN_KEY,JSON.stringify(items));const records=dex();records.push({id:sprite.id,name:sprite.name,rarity:sprite.rarity||'Common',alignment:sprite.alignment||'Unknown',scanCode:sprite.scanCode||'',firstSeen:new Date().toISOString(),captured:false});localStorage.setItem(DEX_KEY,JSON.stringify(records));const m=mission();m.survey=items.length;if(m.survey>=3&&!m.rewarded){m.rewarded=true;addCoins(2);window.dispatchEvent(new CustomEvent('databyte:mission-rewarded',{detail:{coins:2}}))}localStorage.setItem(MISSION_KEY,JSON.stringify(m));window.dispatchEvent(new CustomEvent('databyte:dex-updated'))}}
  function markCaptured(id){const records=dex(),record=records.find(item=>item.id===id);if(record){record.captured=true;record.capturedAt=new Date().toISOString();localStorage.setItem(DEX_KEY,JSON.stringify(records));window.dispatchEvent(new CustomEvent('databyte:dex-updated'))}}
  function scanCode(){return `VL-${Math.random().toString(36).slice(2,8).toUpperCase()}`}
  function rarity(){const roll=Math.random();return roll<.08?'Rare':roll<.28?'Uncommon':'Common'}
  function createEncounter(playerId, currentId){
    const pool=roster().filter(s=>s.id!==playerId && s.id!==currentId);
    const list=pool.length?pool:roster().filter(s=>s.id!==playerId);
    const pending=localStorage.getItem('vl_three_battle_pending_code');let base;if(pending){localStorage.removeItem('vl_three_battle_pending_code');let hash=0;for(const char of pending)hash=(hash*31+char.charCodeAt(0))>>>0;base=list[hash%Math.max(1,list.length)]}else base=list[Math.floor(Math.random()*Math.max(1,list.length))];base=base||{id:'scorpyone',name:'Scorpyone',sprite:'scorpyone.png',color:0xff6689};const runtime=base.runtime||{};return {...base,rarity:base.rarity||rarity(),captureChance:Number(runtime.captureChance)||undefined,maxStability:Number(runtime.stability)||undefined,stability:Number(runtime.stability)||undefined,scanCode:pending||scanCode()};
  }
  function party(){try{return JSON.parse(localStorage.getItem(PARTY_KEY)||'[]')}catch{return[]}}
  function slots(){try{const raw=localStorage.getItem(SLOTS_KEY);let s=raw?JSON.parse(raw):null;const legacy=party();if(!Array.isArray(s))s=Array(5).fill(null);const present=new Set(s.filter(Boolean).map(item=>item.id));for(const item of legacy){if(!item||present.has(item.id))continue;const open=s.findIndex(entry=>!entry);if(open<0)break;s[open]=item;present.add(item.id)}let normalized=Array.from({length:5},(_,i)=>s[i]||null);const activeId=localStorage.getItem('vl_three_battle_starter');const activeIndex=activeId?normalized.findIndex(item=>item?.id===activeId):-1;if(activeIndex>0)[normalized[0],normalized[activeIndex]]=[normalized[activeIndex],normalized[0]];if(normalized[0])localStorage.setItem('vl_three_battle_starter',normalized[0].id);else localStorage.removeItem('vl_three_battle_starter');localStorage.setItem(SLOTS_KEY,JSON.stringify(normalized));localStorage.setItem(PARTY_KEY,JSON.stringify(normalized.filter(Boolean)));return normalized}catch{return Array(5).fill(null)}}
  function assignSlot(index,id){const s=slots(),r=repository(),ri=r.findIndex(x=>x.id===id);if(ri<0)return false;const old=s[index];s[index]=r.splice(ri,1)[0];if(old)r.push(old);localStorage.setItem(SLOTS_KEY,JSON.stringify(s));localStorage.setItem(PARTY_KEY,JSON.stringify(s.filter(Boolean)));localStorage.setItem(REPO_KEY,JSON.stringify(r));setStarter(s[0]?.id||'');window.dispatchEvent(new CustomEvent('databyte:party-updated'));return true}
  function storeSlot(index){const s=slots(),item=s[index];if(!item||index===0)return false;s[index]=null;const r=repository();r.push(item);localStorage.setItem(SLOTS_KEY,JSON.stringify(s));localStorage.setItem(PARTY_KEY,JSON.stringify(s.filter(Boolean)));localStorage.setItem(REPO_KEY,JSON.stringify(r));window.dispatchEvent(new CustomEvent('databyte:party-updated'));return true}
  function swapSlots(a,b){if(a===b)return false;const s=slots();[s[a],s[b]]=[s[b],s[a]];localStorage.setItem(SLOTS_KEY,JSON.stringify(s));localStorage.setItem(PARTY_KEY,JSON.stringify(s.filter(Boolean)));setStarter(s[0]?.id||'');window.dispatchEvent(new CustomEvent('databyte:party-updated'));return true}
  function repository(){try{return JSON.parse(localStorage.getItem(REPO_KEY)||'[]')}catch{return[]}}
  function recoverAll(){const lists=[party(),repository()];for(const list of lists)for(const item of list){item.hp=100;item.recoveryRounds=0}localStorage.setItem(PARTY_KEY,JSON.stringify(lists[0]));localStorage.setItem(REPO_KEY,JSON.stringify(lists[1]));window.dispatchEvent(new CustomEvent('databyte:party-updated'));return true}
  function recoverForScan(amount=10){const lists=[party(),repository()],team=lists[0],tick=Math.max(0,Number(amount)||0);let recovered=0;const allFainted=team.length>0&&team.every(item=>Number(item.hp??100)<=0);if(allFainted){const lead=team.find(item=>item.id===starter())||team[0];lead.hp=25;lead.recoveryRounds=0;recovered+=25}for(const list of lists)for(const item of list){if(allFainted&&list===team&&item===team.find(entry=>entry.id===starter()||entry===team[0]))continue;const before=Math.max(0,Number(item.hp??100));const after=Math.min(100,before+tick);if(after>before){item.hp=after;recovered+=after-before}if(after>0)item.recoveryRounds=0}if(recovered){localStorage.setItem(PARTY_KEY,JSON.stringify(lists[0]));localStorage.setItem(REPO_KEY,JSON.stringify(lists[1]));window.dispatchEvent(new CustomEvent('databyte:party-updated'))}return recovered}
  function advanceRecovery(){const lists=[party(),repository()];let recovered=0;for(const list of lists)for(const item of list){if(Number(item.hp??100)>0)continue;item.recoveryRounds=Number(item.recoveryRounds||0)+1;if(item.recoveryRounds>=2){item.hp=25;item.recoveryRounds=0;recovered++}}if(recovered){localStorage.setItem(PARTY_KEY,JSON.stringify(lists[0]));localStorage.setItem(REPO_KEY,JSON.stringify(lists[1]));window.dispatchEvent(new CustomEvent('databyte:party-updated'))}return recovered}
  function evolve(id){const chains={leovolt:['leovolt','leothor','leozues'],crabician:['crabician','crabizard','crabzaster'],kindlekid:['kindlekid','gaseousgoat','reactorram'],coincalf:['coincalf','cashcow','bankerbull'],scorpyone:['scorpyone','scorpytwo','scorpyus']};const chain=chains[id];if(!chain)return {ok:false,reason:'no-evolution-data'};const from=chain.indexOf(id);if(from<0||from>=chain.length-1)return {ok:false,reason:'max-version'};const nextId=chain[from+1],source=roster().find(item=>item.id===nextId)||{id:nextId,name:nextId,sprite:'placeholder.png'};for(const list of [party(),repository()]){const item=list.find(entry=>entry.id===id);if(item){item.id=source.id;item.name=source.name;item.sprite='./data/sprites/'+(source.sprite||'placeholder.png');item.version=from+2}}localStorage.setItem(PARTY_KEY,JSON.stringify(party()));localStorage.setItem(REPO_KEY,JSON.stringify(repository()));if(starter()===id)localStorage.setItem('vl_three_battle_starter',nextId);window.dispatchEvent(new CustomEvent('databyte:evolved',{detail:{from:id,to:nextId}}));window.dispatchEvent(new CustomEvent('databyte:party-updated'));return {ok:true,from:id,to:nextId}}
  function updateHp(id,hp){const collections=[party(),repository()];let changed=false;for(const list of collections){const item=list.find(x=>x.id===id);if(item){item.hp=Math.max(0,Number(hp)||0);if(item.hp>0)item.recoveryRounds=0;changed=true}}if(changed){localStorage.setItem(PARTY_KEY,JSON.stringify(collections[0]));localStorage.setItem(REPO_KEY,JSON.stringify(collections[1]));window.dispatchEvent(new CustomEvent('databyte:party-updated'))}return changed}
  function attemptCapture(sprite,hp=100,maxHp=100){const chance=Math.round(45+(1-Math.max(0,hp/maxHp))*45);if(Math.random()*100>=chance)return {ok:false,chance};if(!spendCoin())return {ok:false,reason:'no-coins',chance,coins:coins()};return {...capture(sprite),chance}}
  function starter(){return localStorage.getItem('vl_three_battle_starter')||''}
  function setStarter(id){localStorage.setItem('vl_three_battle_starter',id);const items=party();if(id&&!items.some(item=>item.id===id)){const source=roster().find(item=>item.id===id)||{id,name:id,sprite:'placeholder.png'};if(items.length<5){items.unshift({id:source.id,name:source.name,sprite:'./data/sprites/'+(source.sprite||'placeholder.png'),xp:0,level:1});localStorage.setItem(PARTY_KEY,JSON.stringify(items))}}window.dispatchEvent(new CustomEvent('databyte:starter-updated',{detail:{id}}));window.dispatchEvent(new CustomEvent('databyte:party-updated'))}
  function setLead(id){if(party().some(item=>item.id===id)||repository().some(item=>item.id===id))setStarter(id)}
  function deploy(id){const slotsState=slots(),repo=repository(),repoIndex=repo.findIndex(item=>item.id===id);if(repoIndex<0)return false;const next=repo.splice(repoIndex,1)[0],empty=slotsState.findIndex(item=>!item);if(empty>=0){slotsState[empty]=next}else{const activeIndex=Math.max(0,slotsState.findIndex(item=>item?.id===starter())),old=slotsState[activeIndex];slotsState[activeIndex]=next;if(old)repo.push(old)}localStorage.setItem(SLOTS_KEY,JSON.stringify(slotsState));localStorage.setItem(PARTY_KEY,JSON.stringify(slotsState.filter(Boolean)));localStorage.setItem(REPO_KEY,JSON.stringify(repo));setStarter(slotsState[0]?.id||'');window.dispatchEvent(new CustomEvent('databyte:party-updated'));return true}
  function store(id){const items=party(),index=items.findIndex(item=>item.id===id);if(index<0)return false;const [item]=items.splice(index,1),repo=repository();repo.push(item);localStorage.setItem(PARTY_KEY,JSON.stringify(items));localStorage.setItem(REPO_KEY,JSON.stringify(repo));if(starter()===id)setStarter(items[0]?.id||'');window.dispatchEvent(new CustomEvent('databyte:party-updated'));return true}
  function swap(a,b){const items=party(),repo=repository(),ai=items.findIndex(x=>x.id===a),bi=items.findIndex(x=>x.id===b),ar=repo.findIndex(x=>x.id===a),br=repo.findIndex(x=>x.id===b);if(ai>=0&&bi>=0)[items[ai],items[bi]]=[items[bi],items[ai]];else if(ai>=0&&br>=0)[items[ai],repo[br]]=[repo[br],items[ai]];else if(ar>=0&&bi>=0)[repo[ar],items[bi]]=[items[bi],repo[ar]];else return false;localStorage.setItem(PARTY_KEY,JSON.stringify(items));localStorage.setItem(REPO_KEY,JSON.stringify(repo));setStarter(items[0]?.id||'');window.dispatchEvent(new CustomEvent('databyte:party-updated'));return true}
  function capture(sprite){const items=party(),stored={...sprite,id:sprite.id,name:sprite.name,sprite:sprite.sprite,hp:Math.max(0,Number(sprite.hp??100)),maxHp:Number(sprite.maxHp??100),xp:0,level:1};if(items.some(item=>item.id===sprite.id)||repository().some(item=>item.id===sprite.id))return {ok:false,reason:'already-captured',items};if(items.length>=5){const repo=repository();repo.push(stored);localStorage.setItem(REPO_KEY,JSON.stringify(repo));window.dispatchEvent(new CustomEvent('databyte:party-updated'));return {ok:true,location:'repository',items,repository:repo}}items.push(stored);localStorage.setItem(PARTY_KEY,JSON.stringify(items));window.dispatchEvent(new CustomEvent('databyte:party-updated'));return {ok:true,location:'party',items}}
  function evolveFixed(id){const chains={leovolt:['leovolt','leothor','leozues'],crabician:['crabician','crabizard','crabzaster'],kindlekid:['kindlekid','gaseousgoat','reactorram'],coincalf:['coincalf','cashcow','bankerbull'],scorpyone:['scorpyone','scorpytwo','scorpyus']},chain=chains[id],from=chain?.indexOf(id),required=[100,250][from]??0,currentXp=Number(localStorage.getItem('vl_three_battle_xp')||0),wasLead=starter()===id;if(!chain||from<0||from>=chain.length-1)return {ok:false,reason:!chain?'no-evolution-data':'max-version'};if(currentXp<required)return {ok:false,reason:'requires-xp',required,xp:currentXp};const nextId=chain[from+1],source=roster().find(item=>item.id===nextId)||{id:nextId,name:nextId,sprite:'placeholder.png'},active=party(),stored=repository();for(const list of [active,stored]){const item=list.find(entry=>entry.id===id);if(item){item.id=source.id;item.name=source.name;item.sprite='./data/sprites/'+(source.sprite||'placeholder.png');item.version=from+2}}localStorage.setItem(PARTY_KEY,JSON.stringify(active));localStorage.setItem(REPO_KEY,JSON.stringify(stored));if(wasLead)localStorage.setItem('vl_three_battle_starter',nextId);window.dispatchEvent(new CustomEvent('databyte:evolved',{detail:{from:id,to:nextId}}));window.dispatchEvent(new CustomEvent('databyte:party-updated'));return {ok:true,from:id,to:nextId}}
  function exportSave(){return {version:1,exportedAt:new Date().toISOString(),starter:starter(),party:party(),slots:slots(),repository:repository(),seen:seen(),dex:dex(),coins:coins(),mission:mission(),inventory:JSON.parse(localStorage.getItem('vl_three_battle_inventory')||'{}'),xp:Number(localStorage.getItem('vl_three_battle_xp')||0),itemsUsed:Number(localStorage.getItem('vl_three_battle_items_used')||0)}}
  function importSave(payload){let save=payload;try{if(typeof payload==='string')save=JSON.parse(payload)}catch{return {ok:false,reason:'invalid-json'}}if(save&&save.version===undefined)save={...save,version:1};const valid=new Set(roster().map(item=>item.id)),clean=list=>list.filter(item=>item&&typeof item==='object'&&valid.has(item.id));if(!save||save.version!==1||!Array.isArray(save.party)||!Array.isArray(save.repository)||!Array.isArray(save.seen))return {ok:false,reason:'invalid-save'};const safeParty=clean(save.party).slice(0,5),safeRepo=clean(save.repository).filter(item=>!safeParty.some(entry=>entry.id===item.id));localStorage.setItem(PARTY_KEY,JSON.stringify(safeParty));localStorage.setItem(SLOTS_KEY,JSON.stringify(Array.from({length:5},(_,i)=>save.slots?.[i]&&valid.has(save.slots[i].id)?save.slots[i]:safeParty[i]||null)));localStorage.setItem(REPO_KEY,JSON.stringify(safeRepo));localStorage.setItem(SEEN_KEY,JSON.stringify(save.seen.filter(id=>valid.has(id))));localStorage.setItem(DEX_KEY,JSON.stringify(Array.isArray(save.dex)?save.dex.filter(item=>valid.has(item.id)):[]));localStorage.setItem(COIN_KEY,String(Math.max(0,Number(save.coins)||0)));localStorage.setItem(MISSION_KEY,JSON.stringify(save.mission||{survey:save.seen.length,rewarded:false}));localStorage.setItem('vl_three_battle_inventory',JSON.stringify(save.inventory||{}));localStorage.setItem('vl_three_battle_xp',String(Math.max(0,Number(save.xp)||0)));localStorage.setItem('vl_three_battle_items_used',String(Math.max(0,Number(save.itemsUsed)||0)));if(save.starter&&valid.has(save.starter))localStorage.setItem('vl_three_battle_starter',save.starter);window.dispatchEvent(new CustomEvent('databyte:party-updated'));window.dispatchEvent(new CustomEvent('databyte:dex-updated'));window.dispatchEvent(new CustomEvent('databyte:coins-updated'));return {ok:true}}
  function resetSave(){[PARTY_KEY,SLOTS_KEY,REPO_KEY,SEEN_KEY,DEX_KEY,COIN_KEY,MISSION_KEY,'vl_three_battle_starter','vl_three_battle_inventory','vl_three_battle_xp','vl_three_battle_items_used','vl_three_battle_region','vl_three_battle_event_reward','vl_three_battle_discovery_codes','vl_three_battle_pending_code','vl_three_battle_reward_history'].forEach(key=>localStorage.removeItem(key));return true}
  window.DataByteSession={roster,createEncounter,party,slots,repository,assignSlot,storeSlot,swapSlots,capture,attemptCapture,starter,setStarter,setLead,deploy,store,swap,seen,dex,markSeen,markCaptured,coins,addCoins,spendCoin,updateHp,recoverAll,recoverForScan,advanceRecovery,scanCode,mission,profileGet,profileSet,profileRemove,spriteProgress,addSpriteXp,exportSave,importSave,resetSave,evolve:evolveFixed};
})();
(function(){
  const s=window.DataByteSession;
  if(!s||s.capture.__slotAware)return;
  const original=s.capture;
  const captureWithSlots=function(sprite){
    const slots=s.slots(),repo=s.repository();
    if(slots.some(item=>item?.id===sprite.id)||repo.some(item=>item?.id===sprite.id))return {ok:false,reason:'already-captured',items:s.party()};
    const stored={...sprite,id:sprite.id,name:sprite.name,sprite:sprite.sprite,hp:Math.max(0,Number(sprite.hp??100)),maxHp:Number(sprite.maxHp??100),xp:0,level:1};
    const empty=slots.findIndex(item=>!item);
    if(empty<0){
      const nextRepo=[...repo,stored];
      localStorage.setItem('vl_three_battle_slots',JSON.stringify(slots));
      localStorage.setItem('vl_three_battle_party',JSON.stringify(slots.filter(Boolean)));
      localStorage.setItem('vl_three_battle_repository',JSON.stringify(nextRepo));
      window.dispatchEvent(new CustomEvent('databyte:party-updated'));
      return {ok:true,location:'repository',items:slots.filter(Boolean),repository:nextRepo};
    }
    slots[empty]=stored;
    localStorage.setItem('vl_three_battle_slots',JSON.stringify(slots));
    localStorage.setItem('vl_three_battle_party',JSON.stringify(slots.filter(Boolean)));
    window.dispatchEvent(new CustomEvent('databyte:party-updated'));
    return {ok:true,location:'party',items:slots.filter(Boolean)};
  };
  captureWithSlots.__slotAware=true;
  s.capture=captureWithSlots;
})();
