(function(){
  const starter=document.getElementById('starterView'), scanner=document.getElementById('scannerView');
  const session=window.DataByteSession; scanner.classList.add('hidden'); document.body.classList.add('starter-active');
  function activate(id){session.setStarter(id);document.body.classList.remove('starter-active');starter.classList.add('hidden');scanner.classList.remove('hidden','starter-locked');scanner.style.display='block';const scan=document.getElementById('scanBtn');if(scan)scan.disabled=false;document.getElementById('playerName').textContent=id[0].toUpperCase()+id.slice(1);}
  function sourceFor(id){return (window.DataByteSession?.roster?.()||[]).find(item=>item.id===id)||(window.THREE_BATTLE_DATA?.species||[]).find(item=>item.id===id)||{id,name:id,sprite:'placeholder.png',description:'Signal profile pending.'}}
  function closePreview(){document.getElementById('starterPreview')?.remove();document.querySelectorAll('.starter-choice.is-selected').forEach(card=>card.classList.remove('is-selected'))}
  function openPreview(id,card){const source=sourceFor(id),modal=document.createElement('div');modal.id='starterPreview';modal.className='capture-modal is-open';card.classList.add('is-selected');modal.innerHTML=`<div class="capture-card starter-preview-card"><button class="ghost starter-preview-close" data-starter-cancel type="button">CLOSE</button><span class="eyebrow">STARTER SIGNAL // PREVIEW</span><img class="starter-preview-sprite" src="./data/sprites/${source.sprite||'placeholder.png'}" alt="${source.name||id}"><h2>${source.name||id}</h2><p>${source.description||source.lore||'Choose this DataByte to link it to your scanner profile.'}</p><div class="outcome-actions"><button class="scan-button" data-starter-confirm type="button">PICK STARTER</button></div></div>`;document.body.appendChild(modal);modal.querySelector('[data-starter-cancel]').onclick=closePreview;modal.querySelector('[data-starter-confirm]').onclick=()=>{closePreview();activate(id)}}
  const saved=session.starter(); if(saved) activate(saved); document.documentElement.classList.add('dd-ready');
  document.querySelectorAll('[data-starter]').forEach(btn=>btn.addEventListener('click',()=>openPreview(btn.dataset.starter,btn)));
})();
